return {
  -- 'akinsho/flutter-tools.nvim',
  -- lazy = false,
  -- dependencies = {
  --   'nvim-lua/plenary.nvim',
  --   'stevearc/dressing.nvim', -- optional for vim.ui.select
  -- },
  -- config = function()
  --   require('flutter-tools').setup {
  --     lsp = {
  --       color = {
  --         enabled = true,
  --         background = true, -- highlight the background
  --         background_color = { r = 19, g = 17, b = 24 }, -- required, when background is transparent (i.e. background_color = { r = 19, g = 17, b = 24},)
  --         foreground = false, -- highlight the foreground
  --         virtual_text = false, -- show the highlight using virtual text
  --         virtual_text_str = '■', -- the virtual text character to highlight
  --       },
  --       settings = {
  --         showTodos = false,
  --       },
  --     },
  --     -- debugger = { -- integrate with nvim dap + install dart code debugger
  --     --   enabled = true,
  --     --   -- if empty dap will not stop on any exceptions, otherwise it will stop on those specified
  --     --   -- see |:help dap.set_exception_breakpoints()| for more info
  --     --   exception_breakpoints = {},
  --     --   -- Whether to call toString() on objects in debug views like hovers and the
  --     --   -- variables list.
  --     --   -- Invoking toString() has a performance cost and may introduce side-effects,
  --     --   -- although users may expected this functionality. null is treated like false.
  --     --   evaluate_to_string_in_debug_views = true,
  --     --   register_configurations = function(paths)
  --     --     require('dap.ext.vscode').load_launchjs()
  --     --   end,
  --     -- },
  --   }
  --   require('telescope').load_extension 'flutter'
  --   vim.keymap.set('n', '<leader>cfc', '<Cmd>Telescope flutter commands<CR>', { desc = '[C]ode [F]lutter [C]ommands' })
  -- end,
}
